[package]
name = "hlatex"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hlatex"

[dependencies]
askama = "0.12.1"
askama_escape = "0.10.3"
chrono = "0.4.33"
clap = { version = "4.4.18", features = ["derive"] }
clap_complete = "4.4.9"
dialoguer = { version = "0.11.0", default-features = false, features = ["completion"] }
once_cell = "1.19.0"
regex = "1.10.3"

[build-dependencies]
clap = { version = "4.4.18", features = ["derive"] }
clap_complete = "4.4.9"
clap_mangen = "0.2.17"
