[package]
name = "hlatex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hlatex"

[dependencies]
askama = "0.12.0"
askama_escape = "0.10.3"
chrono = "0.4.24"
clap = { version = "4.1.11", features = ["derive"] }
clap_complete = "4.1.5"
dialoguer = { version = "0.10.3", default-features = false, features = ["completion"] }
once_cell = "1.17.1"
regex = "1.7.3"

[build-dependencies]
clap = { version = "4.1.11", features = ["derive"] }
clap_complete = "4.1.5"
clap_mangen = "0.2.10"
